In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a*3)

[ 3  6  9 12 15]


In [ ]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a.shape) #ndaary的形狀
print(a.dtype) #資料的型態
print(a.ndim) #維度

<class 'numpy.ndarray'>
(5,)
int64
1


In [ ]:
import numpy as np
z=np.zeros(6)
print(z)
z=np.zeros((2,3,4))
print(z)
print(np.arange(10))

[0. 0. 0. 0. 0. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [ ]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])
print(my_2d_array[:,1])
print(my_2d_array[1,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [ ]:
a=np.arange(10)
print(a)
print(a.ndim)
b=a.reshape(2,5)
print(b)